insert into pgo.Estado values ('AGUASCALIENTES','AGS')
insert into pgo.Estado values ('BAJA CALIFORNIA','BCN')
insert into pgo.Estado values ('BAJA CALIFORNIA SUR','BCS')
insert into pgo.Estado values ('CAMPECHE','CAMP')
insert into pgo.Estado values ('COAHUILA','COAH')
insert into pgo.Estado values ('COLIMA','COL')
insert into pgo.Estado values ('CHIAPAS','CHIS')
insert into pgo.Estado values ('CHIHUAHUA','CHIH')
insert into pgo.Estado values ('DISTRITO FEDERAL','DF')
insert into pgo.Estado values ('DURANGO','DGO')
insert into pgo.Estado values ('GUANAJUATO','GTO')
insert into pgo.Estado values ('GUERRERO','GRO')
insert into pgo.Estado values ('HIDALGO','HGO')
insert into pgo.Estado values ('JALISCO','JAL')
insert into pgo.Estado values ('ESTADO DE MEXICO','MEX')
insert into pgo.Estado values ('MICHOACAN','MICH')
insert into pgo.Estado values ('MORELOS','MOR')
insert into pgo.Estado values ('NAYARIT','NAY')
insert into pgo.Estado values ('NUEVO LEON','NL')
insert into pgo.Estado values ('OAXACA','OAX')
insert into pgo.Estado values ('PUEBLA','PUE')
insert into pgo.Estado values ('QUERETARO','QRO')
insert into pgo.Estado values ('QUINTANA ROO','QROO')
insert into pgo.Estado values ('SAN LUIS POTOSI','SLP')
insert into pgo.Estado values ('SINALOA','SIN')
insert into pgo.Estado values ('SONORA','SON')
insert into pgo.Estado values ('TABASCO','TAB')
insert into pgo.Estado values ('TAMAULIPAS','TAMP')
insert into pgo.Estado values ('TLAXCALA','TLAX')
insert into pgo.Estado values ('VERACRUZ','VER')
insert into pgo.Estado values ('YUCATAN','YUC')
insert into pgo.Estado values ('ZACATECAS','ZAC')
insert into pgo.Estado values ('CIUDAD DE MÉXICO','CDMX')